services:
  windesapi:
    build: .
    image: windesapi:latest
    container_name: WindesAPI
    ports:
      - "8000:8000"
    environment:
      WINDES_DB_PATH: /app/data/windesapi.db
      RESET_DB_ON_START: "true"
